# Generated by Django 6.1 on 2026-10-08 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_executionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='actual_hours',
        ),
        migrations.AddField(
            model_name='goal',
            name='available_days_per_week',
            field=models.PositiveSmallIntegerField(default=7, help_text='How many days per week you can work on this goal.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
